### ISSUE TITLE
Variable Shadowing issue

### ISSUE THREAD

**Issue by thygrrr** [Karth42/SimpleKeplerOrbits#10]
https://github.com/Karth42/SimpleKeplerOrbits/blob/128493d951b0880a3d6fac94fbcd2d614d332c79/Assets/SimpleKeplerOrbits/Scripts/Data/KeplerOrbitData.cs#L219

I'm porting this library to Unity mathematics, and I found this line of code. There, the instance variable "periapsis" is shadowed by the local one; I wonder if this is intentional because periapsis is subsequently never written in this execution path.

**Comment by Karth42** [comment]
@thygrrr yes, this is an typo. thanks for the find.
