### ISSUE TITLE
How to calculate prograde/retrograde value?

### ISSUE THREAD

**Issue by GodToRun** [Karth42/SimpleKeplerOrbits#12]
Hello. i'm currently working on a game like KSP. so i want to calculate prograde/retrograde value.
i tried velocityHandle.transform.position += velocityHandle.transform.right but it is not perfect solution.
anyone help me?

**Comment by Karth42** [comment]
hi. what do you mean by 'value'? the direction (normal vector)? in this case you can just normalize velocity vector, which will give you prograde direction. from this you can derive everything else. for example, you can add this vector to your body's position to get world space position of prograde point (it seems like this is what you trying to get).
note: velocityHandle transform is not a root source of the orbit data (it's just a simple way to display and manually control velocity), so I would not recommend using it anywhere.
