### ISSUE TITLE
why ecliptic plane is xy, unity3d default plane is xz?

### ISSUE THREAD

**Issue by marsxu1984** [Karth42/SimpleKeplerOrbits#8]
is it easy way to convert it???
![A~59NX~8KAIB%E4@0)6%OJ6](https://user-images.githubusercontent.com/615307/67947414-96290580-fc1e-11e9-89bf-0f4bc67a9cd7.png)

**Comment by Karth42** [comment]
you can easily change ecliptic plane by changing ecliptic basis vectors in the `KeplerOrbitData` file.
