### ISSUE TITLE
How does SimpleKeplerOrbits deal with thrust, if at all?

### ISSUE THREAD

**Issue by DeltaDizzy** [Karth42/SimpleKeplerOrbits#9]
Is there a way to apply forces to a body without using Rigidbody? When I add a Rigidbody, the SimpleKeplerOrbits components seem to stop working, but I don't know of any other way to apply the equivalent of thrust. My use case is a semi-realistic docking simulator, where your thruster firings change your orbit slightly.

**Comment by Karth42** [comment]
You can, for example, call method `CreateNewOrbitFromPositionAndVelocity` every update.
If you will keep KeplerOrbitMover component turned off, it will not conflict with Rigidbody and it will only show the orbit.
